/? CORRECTO: ANALISIS LEXICO
/? | TOKEN | LEXEMA | NUMERO DE LINEA (NUMERO DE COLUMNA) |
/? | constINT | 11 | LINEA 6 (COLUMNA 2) |
/? | constINT | 4 | LINEA 7 (COLUMNA 2) |
/? | idOBJECT | a | LINEA 7 (COLUMNA 3) |
011
04a